---

driver:
  name: vagrant

provisioner:
  name: chef_solo
  solo_rb:
    node_name: tiger-01

platforms:
  - name: debian-wheezy-7
    driver_config:
      box: debian-wheezy-7
      box_url: https://dl.dropboxusercontent.com/s/cd583cuf0mbcix7/debian-wheezy-64-chef.box

suites:
  - name: server
    run_list:
      - recipe[odi-science-tiger::default]
