default['user'] = 'pi'
default['set_fqdn'] = '*'
default['content_repo'] = 'https://github.com/theodi/display-screen-content'
default['overscan']['horizontal'] = '-4'
default['overscan']['vertical'] = '-16'
default['chef_client']['interval'] = '600'
default['chef_client']['splay']       = '30'
